// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.contenidos.negocio.noticias.servicio;

/**
 * <p>
 * vo que tiene los datos de la categoria noticia traducidos al
 * idioma correspondiente.
 * </p>
 */
public class CategoriaNoticiaTraducidaVO
    implements java.io.Serializable
{

    public CategoriaNoticiaTraducidaVO()
    {
    }

    /**
     * Constructor taking all properties.
     */
    public CategoriaNoticiaTraducidaVO(
        java.lang.Long idCategoriaNoticia,
        java.lang.Long idCategoriaIdiomaNoticia,
        java.lang.String idioma,
        java.lang.String nombreCategoria)

    {
        this.idCategoriaNoticia = idCategoriaNoticia;
        this.idCategoriaIdiomaNoticia = idCategoriaIdiomaNoticia;
        this.idioma = idioma;
        this.nombreCategoria = nombreCategoria;
    }

    /**
     * Copies constructor from other CategoriaNoticiaTraducidaVO
     */
    public CategoriaNoticiaTraducidaVO(CategoriaNoticiaTraducidaVO otherBean)
    {
        if (otherBean != null)
        {
            this.idCategoriaNoticia = otherBean.getIdCategoriaNoticia();
            this.idCategoriaIdiomaNoticia = otherBean.getIdCategoriaIdiomaNoticia();
            this.idioma = otherBean.getIdioma();
            this.nombreCategoria = otherBean.getNombreCategoria();
        }
    }

    private java.lang.Long idCategoriaNoticia;

    /**
     * <p>
     * Identificador de la categoria.
     * </p>
     */
    public java.lang.Long getIdCategoriaNoticia()
    {
        return this.idCategoriaNoticia;
    }

    public void setIdCategoriaNoticia(java.lang.Long idCategoriaNoticia)
    {
        this.idCategoriaNoticia = idCategoriaNoticia;
    }

    private java.lang.Long idCategoriaIdiomaNoticia;

    /**
     * <p>
     * Identificador de la categoria traducida al idioma
     * correspondiente.
     * </p>
     */
    public java.lang.Long getIdCategoriaIdiomaNoticia()
    {
        return this.idCategoriaIdiomaNoticia;
    }

    public void setIdCategoriaIdiomaNoticia(java.lang.Long idCategoriaIdiomaNoticia)
    {
        this.idCategoriaIdiomaNoticia = idCategoriaIdiomaNoticia;
    }

    private java.lang.String idioma;

    /**
     * <p>
     * Idioma al que se va a traducir la categoría.
     * </p>
     */
    public java.lang.String getIdioma()
    {
        return this.idioma;
    }

    public void setIdioma(java.lang.String idioma)
    {
        this.idioma = idioma;
    }

    private java.lang.String nombreCategoria;

    /**
     * <p>
     * Nombre de la categoría traducido al idioma correspondiente.
     * </p>
     */
    public java.lang.String getNombreCategoria()
    {
        return this.nombreCategoria;
    }

    public void setNombreCategoria(java.lang.String nombreCategoria)
    {
        this.nombreCategoria = nombreCategoria;
    }

}