// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringDao.vsl in andromda-spring-cartridge.
//
package es.pode.contenidos.negocio.descargas.dominio;

/**
 * @see es.pode.contenidos.negocio.descargas.dominio.DescDescarga
 */
public interface DescDescargaDao
{
    /**
     * This constant is used as a transformation flag; entities can be converted automatically into value objects
     * or other types, different methods in a class implementing this interface support this feature: look for
     * an <code>int</code> parameter called <code>transform</code>.
     * <p/>
     * This specific flag denotes no transformation will occur.
     */
    public final static int TRANSFORM_NONE = 0;

    /**
     * This constant is used as a transformation flag; entities can be converted automatically into value objects
     * or other types, different methods in a class implementing this interface support this feature: look for
     * an <code>int</code> parameter called <code>transform</code>.
     * <p/>
     * This specific flag denotes entities must be transformed into objects of type
     * {@link es.pode.contenidos.negocio.descargas.servicio.DescDescargaVO}.
     */
    public final static int TRANSFORM_DESCDESCARGAVO = 1;

    /**
     * Converts this DAO's entity to an object of type {@link es.pode.contenidos.negocio.descargas.servicio.DescDescargaVO}.
     */
    public es.pode.contenidos.negocio.descargas.servicio.DescDescargaVO toDescDescargaVO(es.pode.contenidos.negocio.descargas.dominio.DescDescarga entity);

    /**
     * Converts this DAO's entity to a Collection of instances of type {@link es.pode.contenidos.negocio.descargas.servicio.DescDescargaVO}.
     */
    public void toDescDescargaVOCollection(java.util.Collection entities);

    public es.pode.contenidos.negocio.descargas.dominio.DescDescarga fromDescDescargaVO(es.pode.contenidos.negocio.descargas.servicio.DescDescargaVO vo);
    
    public void fromDescDescargaVO(es.pode.contenidos.negocio.descargas.servicio.DescDescargaVO vo, es.pode.contenidos.negocio.descargas.dominio.DescDescarga entity);    


    /**
     * Loads an instance of es.pode.contenidos.negocio.descargas.dominio.DescDescarga from the persistent store.
     */
    public es.pode.contenidos.negocio.descargas.dominio.DescDescarga load(java.lang.Long id);

    /**
     * <p>
     *   Does the same thing as {@link #load(java.lang.Long)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined in this class then the result <strong>WILL BE</strong> passed through an operation which can
     *   optionally transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     *
     * @param id the identifier of the entity to load.
     * @return either the entity or the object transformed from the entity.
     */
    public Object load(int transform, java.lang.Long id);
    
    /**
     * Loads all entities of type {@link es.pode.contenidos.negocio.descargas.dominio.DescDescarga}. 
     * 
     * @return the loaded entities.
     */
    public java.util.Collection loadAll();
    
    /** 
     * <p>
     *   Does the same thing as {@link #loadAll()} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     * 
     * @param transform the flag indicating what transformation to use.
     * @return the loaded entities.
     */
    public java.util.Collection loadAll(final int transform);

    /**
     * Creates an instance of es.pode.contenidos.negocio.descargas.dominio.DescDescarga and adds it to the persistent store.
     */
    public es.pode.contenidos.negocio.descargas.dominio.DescDescarga create(es.pode.contenidos.negocio.descargas.dominio.DescDescarga descDescarga);

    /**
     * <p>
     *   Does the same thing as {@link #create(es.pode.contenidos.negocio.descargas.dominio.DescDescarga)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     */
    public Object create(int transform, es.pode.contenidos.negocio.descargas.dominio.DescDescarga descDescarga);

    /**
     * Creates a new instance of es.pode.contenidos.negocio.descargas.dominio.DescDescarga and adds
     * from the passed in <code>entities</code> collection
     *
     * @param entities the collection of es.pode.contenidos.negocio.descargas.dominio.DescDescarga
     *        instances to create.
     *
     * @return the created instances.
     */
    public java.util.Collection create(java.util.Collection entities);

    /**
     * <p>
     *   Does the same thing as {@link #create(es.pode.contenidos.negocio.descargas.dominio.DescDescarga)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entities (into value objects for example).  By default, transformation does
     *   not occur.
     * </p>
     */
    public java.util.Collection create(int transform, java.util.Collection entities);

    /**
     * <p>
     *   Creates a new <code>es.pode.contenidos.negocio.descargas.dominio.DescDescarga</code>
     *   instance from <strong>all</strong> attributes and adds it to
     *   the persistent store.
     * </p>
     */
    public es.pode.contenidos.negocio.descargas.dominio.DescDescarga create(
        java.lang.String idioma,
        java.lang.String descripcion,
        java.lang.String titulo);

    /**
     * <p>
     *   Does the same thing as {@link #create(java.lang.String, java.lang.String, java.lang.String)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     */
    public Object create(
        int transform,
        java.lang.String idioma,
        java.lang.String descripcion,
        java.lang.String titulo);

    /**
     * <p>
     *  Creates a new <code>es.pode.contenidos.negocio.descargas.dominio.DescDescarga</code>
     *  instance from only <strong>required</strong> properties (attributes
     *  and association ends) and adds it to the persistent store.
     * </p>
     */
    public es.pode.contenidos.negocio.descargas.dominio.DescDescarga create(
        es.pode.contenidos.negocio.descargas.dominio.Descarga descarga,
        java.lang.String descripcion,
        java.lang.String idioma,
        java.lang.String titulo);

    /**
     * <p>
     *   Does the same thing as {@link #create(java.lang.String, java.lang.String, java.lang.String)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     */
    public Object create(
        int transform,
        es.pode.contenidos.negocio.descargas.dominio.Descarga descarga,
        java.lang.String descripcion,
        java.lang.String idioma,
        java.lang.String titulo);

    /**
     * Updates the <code>descDescarga</code> instance in the persistent store.
     */
    public void update(es.pode.contenidos.negocio.descargas.dominio.DescDescarga descDescarga);

    /**
     * Updates all instances in the <code>entities</code> collection in the persistent store.
     */
    public void update(java.util.Collection entities);

    /**
     * Removes the instance of es.pode.contenidos.negocio.descargas.dominio.DescDescarga from the persistent store.
     */
    public void remove(es.pode.contenidos.negocio.descargas.dominio.DescDescarga descDescarga);

    /**
     * Removes the instance of es.pode.contenidos.negocio.descargas.dominio.DescDescarga having the given
     * <code>identifier</code> from the persistent store.
     */
    public void remove(java.lang.Long id);

    /**
     * Removes all entities in the given <code>entities<code> collection.
     */
    public void remove(java.util.Collection entities);

    /**
     * 
     */
    public java.util.Collection obtenerDescDescarga(es.pode.contenidos.negocio.descargas.dominio.DescDescargaCriteria criteria);

    /**
     * <p>
     *   Does the same thing as {@link #obtenerDescDescarga(es.pode.contenidos.negocio.descargas.dominio.DescDescargaCriteria)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   finder results will <strong>NOT</strong> be transformed during retrieval.
     *   If this flag is any of the other constants defined here
     *   then finder results <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entities (into value objects for example).  By default, transformation does
     *   not occur.
     * </p>
     */
    public java.util.Collection obtenerDescDescarga(final int transform, final es.pode.contenidos.negocio.descargas.dominio.DescDescargaCriteria criteria);

}
