// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.buscar.negocio.buscar.servicios;

/**
 * 
 */
public class ParamBusquedaSQIVO
    implements java.io.Serializable
{

    public ParamBusquedaSQIVO()
    {
    }

    /**
     * Constructor taking all properties.
     */
    public ParamBusquedaSQIVO(
        java.lang.String palabrasClave,
        java.lang.Integer origenPagina,
        java.lang.Integer numeroResultados,
        java.lang.Integer resultadoPorPagina)

    {
        this.palabrasClave = palabrasClave;
        this.origenPagina = origenPagina;
        this.numeroResultados = numeroResultados;
        this.resultadoPorPagina = resultadoPorPagina;
    }

    /**
     * Copies constructor from other ParamBusquedaSQIVO
     */
    public ParamBusquedaSQIVO(ParamBusquedaSQIVO otherBean)
    {
        if (otherBean != null)
        {
            this.palabrasClave = otherBean.getPalabrasClave();
            this.origenPagina = otherBean.getOrigenPagina();
            this.numeroResultados = otherBean.getNumeroResultados();
            this.resultadoPorPagina = otherBean.getResultadoPorPagina();
        }
    }

    private java.lang.String palabrasClave;

    /**
     * <p>
     * Palabras a buscar
     * </p>
     */
    public java.lang.String getPalabrasClave()
    {
        return this.palabrasClave;
    }

    public void setPalabrasClave(java.lang.String palabrasClave)
    {
        this.palabrasClave = palabrasClave;
    }

    private java.lang.Integer origenPagina;

    /**
     * 
     */
    public java.lang.Integer getOrigenPagina()
    {
        return this.origenPagina;
    }

    public void setOrigenPagina(java.lang.Integer origenPagina)
    {
        this.origenPagina = origenPagina;
    }

    private java.lang.Integer numeroResultados;

    /**
     * 
     */
    public java.lang.Integer getNumeroResultados()
    {
        return this.numeroResultados;
    }

    public void setNumeroResultados(java.lang.Integer numeroResultados)
    {
        this.numeroResultados = numeroResultados;
    }

    private java.lang.Integer resultadoPorPagina;

    /**
     * 
     */
    public java.lang.Integer getResultadoPorPagina()
    {
        return this.resultadoPorPagina;
    }

    public void setResultadoPorPagina(java.lang.Integer resultadoPorPagina)
    {
        this.resultadoPorPagina = resultadoPorPagina;
    }

}