// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.buscar.negocio.buscar.servicios;

/**
 * <p>
 * Parámetros para la solicitud de documentos existentes en el
 * índice para un área curricular.
 * </p>
 */
public class ParametrosNodoArbolCurricularVO
    implements java.io.Serializable
{

    public ParametrosNodoArbolCurricularVO()
    {
    }

    /**
     * Constructor taking all properties.
     */
    public ParametrosNodoArbolCurricularVO(
        java.lang.String idiomaBusqueda,
        java.lang.String areaCurricular,
        java.lang.Integer numeroResultados,
        java.lang.String idiomaNavegacion,
        java.lang.Integer origenPagina,
        java.lang.Integer resultadoPagina,
        java.lang.String idBusqueda,
        java.lang.String tipoBusqueda,
        java.lang.String comunidadPeticion)

    {
        this.idiomaBusqueda = idiomaBusqueda;
        this.areaCurricular = areaCurricular;
        this.numeroResultados = numeroResultados;
        this.idiomaNavegacion = idiomaNavegacion;
        this.origenPagina = origenPagina;
        this.resultadoPagina = resultadoPagina;
        this.idBusqueda = idBusqueda;
        this.tipoBusqueda = tipoBusqueda;
        this.comunidadPeticion = comunidadPeticion;
    }

    /**
     * Copies constructor from other ParametrosNodoArbolCurricularVO
     */
    public ParametrosNodoArbolCurricularVO(ParametrosNodoArbolCurricularVO otherBean)
    {
        if (otherBean != null)
        {
            this.idiomaBusqueda = otherBean.getIdiomaBusqueda();
            this.areaCurricular = otherBean.getAreaCurricular();
            this.numeroResultados = otherBean.getNumeroResultados();
            this.idiomaNavegacion = otherBean.getIdiomaNavegacion();
            this.origenPagina = otherBean.getOrigenPagina();
            this.resultadoPagina = otherBean.getResultadoPagina();
            this.idBusqueda = otherBean.getIdBusqueda();
            this.tipoBusqueda = otherBean.getTipoBusqueda();
            this.comunidadPeticion = otherBean.getComunidadPeticion();
        }
    }

    private java.lang.String idiomaBusqueda;

    /**
     * 
     */
    public java.lang.String getIdiomaBusqueda()
    {
        return this.idiomaBusqueda;
    }

    public void setIdiomaBusqueda(java.lang.String idiomaBusqueda)
    {
        this.idiomaBusqueda = idiomaBusqueda;
    }

    private java.lang.String areaCurricular;

    /**
     * 
     */
    public java.lang.String getAreaCurricular()
    {
        return this.areaCurricular;
    }

    public void setAreaCurricular(java.lang.String areaCurricular)
    {
        this.areaCurricular = areaCurricular;
    }

    private java.lang.Integer numeroResultados;

    /**
     * 
     */
    public java.lang.Integer getNumeroResultados()
    {
        return this.numeroResultados;
    }

    public void setNumeroResultados(java.lang.Integer numeroResultados)
    {
        this.numeroResultados = numeroResultados;
    }

    private java.lang.String idiomaNavegacion;

    /**
     * 
     */
    public java.lang.String getIdiomaNavegacion()
    {
        return this.idiomaNavegacion;
    }

    public void setIdiomaNavegacion(java.lang.String idiomaNavegacion)
    {
        this.idiomaNavegacion = idiomaNavegacion;
    }

    private java.lang.Integer origenPagina;

    /**
     * 
     */
    public java.lang.Integer getOrigenPagina()
    {
        return this.origenPagina;
    }

    public void setOrigenPagina(java.lang.Integer origenPagina)
    {
        this.origenPagina = origenPagina;
    }

    private java.lang.Integer resultadoPagina;

    /**
     * 
     */
    public java.lang.Integer getResultadoPagina()
    {
        return this.resultadoPagina;
    }

    public void setResultadoPagina(java.lang.Integer resultadoPagina)
    {
        this.resultadoPagina = resultadoPagina;
    }

    private java.lang.String idBusqueda;

    /**
     * 
     */
    public java.lang.String getIdBusqueda()
    {
        return this.idBusqueda;
    }

    public void setIdBusqueda(java.lang.String idBusqueda)
    {
        this.idBusqueda = idBusqueda;
    }

    private java.lang.String tipoBusqueda;

    /**
     * 
     */
    public java.lang.String getTipoBusqueda()
    {
        return this.tipoBusqueda;
    }

    public void setTipoBusqueda(java.lang.String tipoBusqueda)
    {
        this.tipoBusqueda = tipoBusqueda;
    }

    private java.lang.String comunidadPeticion;

    /**
     * 
     */
    public java.lang.String getComunidadPeticion()
    {
        return this.comunidadPeticion;
    }

    public void setComunidadPeticion(java.lang.String comunidadPeticion)
    {
        this.comunidadPeticion = comunidadPeticion;
    }

}