// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.buscar.negocio.buscar.servicios;

/**
 * <p>
 * Parámetros para solicitar el número de documentos para un área
 * curricular
 * </p>
 */
public class ParametrosDocsCountVO
    implements java.io.Serializable
{

    public ParametrosDocsCountVO()
    {
    }

    /**
     * Constructor taking all properties.
     */
    public ParametrosDocsCountVO(
        java.lang.String idiomaBusqueda,
        java.lang.String[] areaCurricular,
        java.lang.String idiomaNavegacion,
        java.lang.String tipoBusqueda,
        java.lang.String comunidadPeticion,
        java.lang.String arbolCurricularVigente,
        java.lang.String[] tesauros)

    {
        this.idiomaBusqueda = idiomaBusqueda;
        this.areaCurricular = areaCurricular;
        this.idiomaNavegacion = idiomaNavegacion;
        this.tipoBusqueda = tipoBusqueda;
        this.comunidadPeticion = comunidadPeticion;
        this.arbolCurricularVigente = arbolCurricularVigente;
        this.tesauros = tesauros;
    }

    /**
     * Copies constructor from other ParametrosDocsCountVO
     */
    public ParametrosDocsCountVO(ParametrosDocsCountVO otherBean)
    {
        if (otherBean != null)
        {
            this.idiomaBusqueda = otherBean.getIdiomaBusqueda();
            this.areaCurricular = otherBean.getAreaCurricular();
            this.idiomaNavegacion = otherBean.getIdiomaNavegacion();
            this.tipoBusqueda = otherBean.getTipoBusqueda();
            this.comunidadPeticion = otherBean.getComunidadPeticion();
            this.arbolCurricularVigente = otherBean.getArbolCurricularVigente();
            this.tesauros = otherBean.getTesauros();
        }
    }

    private java.lang.String idiomaBusqueda;

    /**
     * 
     */
    public java.lang.String getIdiomaBusqueda()
    {
        return this.idiomaBusqueda;
    }

    public void setIdiomaBusqueda(java.lang.String idiomaBusqueda)
    {
        this.idiomaBusqueda = idiomaBusqueda;
    }

    private java.lang.String[] areaCurricular;

    /**
     * 
     */
    public java.lang.String[] getAreaCurricular()
    {
        return this.areaCurricular;
    }

    public void setAreaCurricular(java.lang.String[] areaCurricular)
    {
        this.areaCurricular = areaCurricular;
    }

    private java.lang.String idiomaNavegacion;

    /**
     * 
     */
    public java.lang.String getIdiomaNavegacion()
    {
        return this.idiomaNavegacion;
    }

    public void setIdiomaNavegacion(java.lang.String idiomaNavegacion)
    {
        this.idiomaNavegacion = idiomaNavegacion;
    }

    private java.lang.String tipoBusqueda;

    /**
     * 
     */
    public java.lang.String getTipoBusqueda()
    {
        return this.tipoBusqueda;
    }

    public void setTipoBusqueda(java.lang.String tipoBusqueda)
    {
        this.tipoBusqueda = tipoBusqueda;
    }

    private java.lang.String comunidadPeticion;

    /**
     * 
     */
    public java.lang.String getComunidadPeticion()
    {
        return this.comunidadPeticion;
    }

    public void setComunidadPeticion(java.lang.String comunidadPeticion)
    {
        this.comunidadPeticion = comunidadPeticion;
    }

    private java.lang.String arbolCurricularVigente;

    /**
     * 
     */
    public java.lang.String getArbolCurricularVigente()
    {
        return this.arbolCurricularVigente;
    }

    public void setArbolCurricularVigente(java.lang.String arbolCurricularVigente)
    {
        this.arbolCurricularVigente = arbolCurricularVigente;
    }

    private java.lang.String[] tesauros;

    /**
     * 
     */
    public java.lang.String[] getTesauros()
    {
        return this.tesauros;
    }

    public void setTesauros(java.lang.String[] tesauros)
    {
        this.tesauros = tesauros;
    }

}