// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringServiceBase.vsl in andromda-spring-cartridge.
//
package es.pode.valoracion.negocio.servicios.auditoria;

import net.sf.dozer.util.mapping.MapperIF;

import org.apache.log4j.Logger;


/**
 * <p>
 * Spring Service base class for <code>es.pode.valoracion.negocio.servicios.auditoria.SrvAuditoriaValoracionService</code>,
 * provides access to all services and entities referenced by this service.
 * </p>
 *
 * @see es.pode.valoracion.negocio.servicios.auditoria.SrvAuditoriaValoracionService
 */
public abstract class SrvAuditoriaValoracionServiceBase
    implements es.pode.valoracion.negocio.servicios.auditoria.SrvAuditoriaValoracionService
{

		 protected static final Logger logger = Logger.getLogger(SrvAuditoriaValoracionServiceBase.class);


	
	/**
	 * Reference to the dozer bean mapper used in the application (singleton).
	 */
	private MapperIF beanMapper;
	
	/**
	 * Gets the reference to the dozer bean mapper used in the application (singleton).
	 * @return MapperIF
	 */
    protected MapperIF getBeanMapper() {
		return beanMapper;
	}

    /**
     * Sets the instance of the Dozer bean mapper to be used.
     * @param beanMapper
     */
	public void setBeanMapper(MapperIF beanMapper) {
		this.beanMapper = beanMapper;
	}


	
	        
    
	    	    private es.pode.valoracion.negocio.servicios.SrvValoracionService srvValoracionService;
	
	    /**
	     * Sets the reference to <code>srvValoracionService</code>.
	     */
	    public void setSrvValoracionService(es.pode.valoracion.negocio.servicios.SrvValoracionService srvValoracionService)
	    {
	        this.srvValoracionService = srvValoracionService;
	    }
	
	    /**
	     * Gets the reference to <code>srvValoracionService</code>.
	     */
	    protected es.pode.valoracion.negocio.servicios.SrvValoracionService getSrvValoracionService()
	    {
	        return this.srvValoracionService;
	    }
	    
	        
    private es.pode.valoracion.negocio.dominio.ValoracionDao valoracionDao;

    /**
     * Sets the reference to <code>valoracion</code>'s DAO.
     */
    public void setValoracionDao(es.pode.valoracion.negocio.dominio.ValoracionDao valoracionDao)
    {
        this.valoracionDao = valoracionDao;
    }

    /**
     * Gets the reference to <code>valoracion</code>'s DAO.
     */
    protected es.pode.valoracion.negocio.dominio.ValoracionDao getValoracionDao()
    {
        return this.valoracionDao;
    }


    /**
     * @see es.pode.valoracion.negocio.servicios.auditoria.SrvAuditoriaValoracionService#contenidosMasValorados(es.pode.valoracion.negocio.servicios.auditoria.ParametroAuditValoracionVO)
     */
    public es.pode.valoracion.negocio.servicios.auditoria.ValoracionODEVO[] contenidosMasValorados(es.pode.valoracion.negocio.servicios.auditoria.ParametroAuditValoracionVO parametro)
    {
        if (parametro == null)
        {
            throw new IllegalArgumentException(
                "es.pode.valoracion.negocio.servicios.auditoria.SrvAuditoriaValoracionService.contenidosMasValorados(es.pode.valoracion.negocio.servicios.auditoria.ParametroAuditValoracionVO parametro) - 'parametro' can not be null");
        }
        try
        {
            return this.handleContenidosMasValorados(parametro);
        }
        catch (Throwable th)
        {
            throw new es.pode.valoracion.negocio.servicios.auditoria.SrvAuditoriaValoracionServiceException(
                "Error performing 'es.pode.valoracion.negocio.servicios.auditoria.SrvAuditoriaValoracionService.contenidosMasValorados(es.pode.valoracion.negocio.servicios.auditoria.ParametroAuditValoracionVO parametro)' --> " + th,
                th);
        }
    }

     /**
      * Performs the core logic for {@link #contenidosMasValorados(es.pode.valoracion.negocio.servicios.auditoria.ParametroAuditValoracionVO)}
      */
    protected abstract es.pode.valoracion.negocio.servicios.auditoria.ValoracionODEVO[] handleContenidosMasValorados(es.pode.valoracion.negocio.servicios.auditoria.ParametroAuditValoracionVO parametro)
        throws java.lang.Exception;

    /**
     * Gets the current <code>principal</code> if one has been set,
     * otherwise returns <code>null</code>.
     *
     * @return the current principal
     */
    protected java.security.Principal getPrincipal()
    {
        return es.pode.PrincipalStore.get();
    }
}