// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringService.vsl in andromda-spring-cartridge.
//
package es.pode.publicacion.negocio.servicios;

/**
 * <p>
 * Este servicio implementa toda la funcionalidad de auditoria del
 * servico de publicacion. Es la puerta de entrada a la informacion
 * estadistica relevante que se puede generar en el modulo de
 * publicacion.
 * </p>
 */
public interface SrvAuditaPublicacionService
{
  /**
   * <p>
   * Este metodo devuelve para cada estado posible de un ODE, el
   * numero de transiciones que se han detectado para cada estado en
   * el periodo dado.
   * </p>
      * @param parametroAuditoria  Parametro de auditoria con toda la informacion necesaria.
      * @return es.pode.publicacion.negocio.servicios.ODEsEstadoVO[]
   */
    public es.pode.publicacion.negocio.servicios.ODEsEstadoVO[] actividadTransiciones(es.pode.publicacion.negocio.servicios.ParametroAuditPublicacionVO parametroAuditoria);

  /**
   * <p>
   * Este metodo devuelve el tamanio de los ODEs que estan publicados
   * en la plataforma.
   * </p>
   * <p>
   * Se le pasa la fecha desde y hasta que se quiere tener en cuenta
   * y el numero de ODEs que se quieren devolver.
   * </p>
   * <p>
   * Se devuelve una lista de la cantidad de informacion pedida
   * ordenada de mayor a menor de los mas pesados a los menos.
   * </p>
      * @param parametroAuditoria  Parametro de auditoria con toda la informacion necesaria.
      * @return es.pode.publicacion.negocio.servicios.PesoODEVO[]
   */
    public es.pode.publicacion.negocio.servicios.PesoODEVO[] dimensionesODEsPublicados(es.pode.publicacion.negocio.servicios.ParametroAuditPublicacionVO parametroAuditoria);

  /**
   * <p>
   * Este metodo devuelve la cantidad de ODEs que hay en cada estado
   * dentro del periodo de tiempo dado.
   * </p>
      * @param parametroAuditoria  Parametro de auditoria con toda la informacion necesaria.
      * @return es.pode.publicacion.negocio.servicios.ODEsEstadoVO[]
   */
    public es.pode.publicacion.negocio.servicios.ODEsEstadoVO[] odesPorEstados(es.pode.publicacion.negocio.servicios.ParametroAuditPublicacionVO parametroAuditoria);

  /**
   * <p>
   * Este metodo devuelve el listado de ODEs que un usuario tiene
   * asociado por estado dentro del ciclo de vida definido en el
   * modulo de publicacion.
   * </p>
      * @param parametroAuditoria  Parametro de auditoria con toda la informacion necesaria.
      * @return es.pode.publicacion.negocio.servicios.EstadoActividadVO[]
   */
    public es.pode.publicacion.negocio.servicios.EstadoActividadVO[] odesPorUsuario(es.pode.publicacion.negocio.servicios.ParametroAuditPublicacionVO parametroAuditoria);

  /**
   * <p>
   * Este metodo devuelve la informacion de detalle de la lista de
   * identificadores que le pasan.
   * </p>
      * @param idODEs  Lista de los identificadores que le pasan.
      * @return es.pode.publicacion.negocio.servicios.DetallePublicadoODEVO[]
   */
    public es.pode.publicacion.negocio.servicios.DetallePublicadoODEVO[] titulosODEsPorID(java.lang.String[] idODEs);

  /**
   * <p>
   * Obtiene los n últimos odes publicados.
   * </p>
   * <p>
   * Parametro de entrada: entero con el numero de odes que se
   * quieren obtener.
   * </p>
   * <p>
   * Parametro de salida: array de vo con los n últimos odes
   * publicados.
   * </p>
      * @param numeroOdes  Número de odes publicados que se quieren obtener.
      * @return es.pode.publicacion.negocio.servicios.OdePublicadoVO[]
   */
    public es.pode.publicacion.negocio.servicios.OdePublicadoVO[] obtenerUltimosOdesPublicados(int numeroOdes);

  /**
   * <p>
   * Este metodo devuelve el numero de ODEs publicados en la
   * plataforma.
   * </p>
   * @return es.pode.publicacion.negocio.servicios.ODEsEstadoVO
   */
    public es.pode.publicacion.negocio.servicios.ODEsEstadoVO odesPublicados();

  /**
   * <p>
   * Este metodo devuelve el numero de ODEs que hay publicados por
   * idiomas.
   * </p>
   * @return es.pode.publicacion.negocio.servicios.ODEsEstadoIdiomaVO[]
   */
    public es.pode.publicacion.negocio.servicios.ODEsEstadoIdiomaVO[] odesPublicadosPorIdioma();

}
