// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SearchCriteria.vsl in andromda-spring-cartridge.
//
package es.pode.auditoria.negocio.dominio;

/**
 * <p>
 * Este criterio obtiene el listado de los odes asociados a una
 * determinada operación y para un usuario concreto entre dos
 * fechas concretas
 * </p>
 */
public class TitulosOdePorUsuarioDesdeHastaCriteria
    implements java.io.Serializable
{

  /**
   * Constructor por defecto
   */
    public TitulosOdePorUsuarioDesdeHastaCriteria()
    {
    }

    /**
     * Constructor taking all properties.
      * @param fechaDesde java.util.Calendar
      * @param fechaHasta java.util.Calendar
      * @param usuario java.lang.String
      * @param operacion java.lang.String
     */
    public TitulosOdePorUsuarioDesdeHastaCriteria(
        java.util.Calendar fechaDesde,
        java.util.Calendar fechaHasta,
        java.lang.String usuario,
        java.lang.String operacion)

    {
        this.fechaDesde = fechaDesde;
        this.fechaHasta = fechaHasta;
        this.usuario = usuario;
        this.operacion = operacion;
    }

    /**
     * Copies constructor from other TitulosOdePorUsuarioDesdeHastaCriteria
      * @param otherBean TitulosOdePorUsuarioDesdeHastaCriteria
     */
    public TitulosOdePorUsuarioDesdeHastaCriteria(TitulosOdePorUsuarioDesdeHastaCriteria otherBean)
    {
        if (otherBean != null)
        {
            this.fechaDesde = otherBean.getFechaDesde();
            this.fechaHasta = otherBean.getFechaHasta();
            this.usuario = otherBean.getUsuario();
            this.operacion = otherBean.getOperacion();
        }
    }

    /**
     * The first result to retrieve.
     */
    private java.lang.Integer firstResult;

    /**
     * Gets the first result to retrieve.
     *
     * @return the first result to retrieve
     */
    public java.lang.Integer getFirstResult()
    {
        return this.firstResult;
    }

    /**
     * Sets the first result to retrieve.
     *
     * @param firstResult the first result to retrieve
     */
    public void setFirstResult(java.lang.Integer firstResult)
    {
        this.firstResult = firstResult;
    }

    /**
     * The fetch size.
     */
    private java.lang.Integer fetchSize;

    /**
     * Gets the fetch size.
     *
     * @return the fetch size
     */
    public java.lang.Integer getFetchSize()
    {
        return this.fetchSize;
    }

    /**
     * Sets the fetch size.
     *
     * @param fetchSize the fetch size
     */
    public void setFetchSize(java.lang.Integer fetchSize)
    {
        this.fetchSize = fetchSize;
    }

    /**
     * The maximum size of the result set.
     */
    private java.lang.Integer maximumResultSize;

    /**
     * Gets the maximum size of the search result.
     *
     * @return the maximum size of the search result.
     */
    public java.lang.Integer getMaximumResultSize()
    {
        return this.maximumResultSize;
    }

    /**
     * Sets the maxmimum size of the result.
     *
     * @param maximumResultSize A number indicating how many results will be returned.
     */
    public void setMaximumResultSize(java.lang.Integer maximumResultSize)
    {
        this.maximumResultSize = maximumResultSize;
    }

    private java.util.Calendar fechaDesde;

    public java.util.Calendar getFechaDesde()
    {
        return this.fechaDesde;
    }

    public void setFechaDesde(java.util.Calendar fechaDesde)
    {
        this.fechaDesde = fechaDesde;
    }

    private java.util.Calendar fechaHasta;

    public java.util.Calendar getFechaHasta()
    {
        return this.fechaHasta;
    }

    public void setFechaHasta(java.util.Calendar fechaHasta)
    {
        this.fechaHasta = fechaHasta;
    }

    private java.lang.String usuario;

    public java.lang.String getUsuario()
    {
        return this.usuario;
    }

    public void setUsuario(java.lang.String usuario)
    {
        this.usuario = usuario;
    }

    private java.lang.String operacion;

    public java.lang.String getOperacion()
    {
        return this.operacion;
    }

    public void setOperacion(java.lang.String operacion)
    {
        this.operacion = operacion;
    }

}