// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.modificador.negocio.servicio;

/**
 * 
 */
public class ModificacionSimuladaVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public ModificacionSimuladaVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param resultado  
     * @param msgError  Mensaje de error asociado a la modificacion. Se representaran con códigos para facilitar su internacionalizacion.
     * @param resultados  
     */
    public ModificacionSimuladaVO(
        es.pode.modificador.negocio.utilidades.EstadosTarea resultado,
        java.lang.String msgError,
        es.pode.modificador.negocio.servicio.ResultadoModificacionVO[] resultados)

    {
        this.resultado = resultado;
        this.msgError = msgError;
        this.resultados = resultados;
    }

    /**
     * Copies constructor from other ModificacionSimuladaVO
     * @param otherBean ModificacionSimuladaVO 
     */
    public ModificacionSimuladaVO(ModificacionSimuladaVO otherBean)
    {
        if (otherBean != null)
        {
            this.resultado = otherBean.getResultado();
            this.msgError = otherBean.getMsgError();
            this.resultados = otherBean.getResultados();
        }
    }

    private es.pode.modificador.negocio.utilidades.EstadosTarea resultado;

    public es.pode.modificador.negocio.utilidades.EstadosTarea getResultado()
    {
        return this.resultado;
    }

    public void setResultado(es.pode.modificador.negocio.utilidades.EstadosTarea resultado)
    {
        this.resultado = resultado;
    }

    private java.lang.String msgError;

    /**
     * <p>
     * Mensaje de error asociado a la modificacion. Se representaran
     * con códigos para facilitar su internacionalizacion.
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getMsgError()
    {
        return this.msgError;
    }

    /**
   * <p>
   * Mensaje de error asociado a la modificacion. Se representaran
   * con códigos para facilitar su internacionalizacion.
   * </p>
     *  @param msgError  Mensaje de error asociado a la modificacion. Se representaran con códigos para facilitar su internacionalizacion.  
     */
    public void setMsgError(java.lang.String msgError)
    {
        this.msgError = msgError;
    }

    /**
   * 
     */
    private es.pode.modificador.negocio.servicio.ResultadoModificacionVO[] resultados;

    public es.pode.modificador.negocio.servicio.ResultadoModificacionVO[] getResultados()
    {
        return this.resultados;
    }

    public void setResultados(es.pode.modificador.negocio.servicio.ResultadoModificacionVO[] resultados)
    {
        this.resultados = resultados;
    }

}