// license-header java merge-point
/* Autogenerated by AndroMDA (MessageDrivenBean.vsl) - do not edit */

package es.pode.modificador.negocio.servicio;

import java.util.Map;


/**
 * Autogenerated JMS message driven EJB class for the SrvTareasModificacionService bean.
 * Generated file: es/pode/modificador/negocio/servicio/SrvTareasModificacionService
 */



public interface  SrvTareasModificacionService 
{
    

    

    // -------- User Defined Methods  --------------
    

  
  
        public  java.lang.Boolean ejecutarTareaModificacion(java.lang.Long idModificacion);
   
  
 
}