// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.modificador.negocio.servicio;

/**
 * 
 */
public class TaxonVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public TaxonVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param valorTax  
     * @param id  
     * @param esHoja  
     * @param tipoRelacion  
     * @param vocabName  
     */
    public TaxonVO(
        java.lang.String valorTax,
        java.lang.String id,
        java.lang.Boolean esHoja,
        java.lang.String tipoRelacion,
        java.lang.String vocabName)

    {
        this.valorTax = valorTax;
        this.id = id;
        this.esHoja = esHoja;
        this.tipoRelacion = tipoRelacion;
        this.vocabName = vocabName;
    }

    /**
     * Copies constructor from other TaxonVO
     * @param otherBean TaxonVO 
     */
    public TaxonVO(TaxonVO otherBean)
    {
        if (otherBean != null)
        {
            this.valorTax = otherBean.getValorTax();
            this.id = otherBean.getId();
            this.esHoja = otherBean.getEsHoja();
            this.tipoRelacion = otherBean.getTipoRelacion();
            this.vocabName = otherBean.getVocabName();
        }
    }

    private java.lang.String valorTax;

    public java.lang.String getValorTax()
    {
        return this.valorTax;
    }

    public void setValorTax(java.lang.String valorTax)
    {
        this.valorTax = valorTax;
    }

    private java.lang.String id;

    public java.lang.String getId()
    {
        return this.id;
    }

    public void setId(java.lang.String id)
    {
        this.id = id;
    }

    private java.lang.Boolean esHoja;

    public java.lang.Boolean getEsHoja()
    {
        return this.esHoja;
    }

    public void setEsHoja(java.lang.Boolean esHoja)
    {
        this.esHoja = esHoja;
    }

    private java.lang.String tipoRelacion;

    public java.lang.String getTipoRelacion()
    {
        return this.tipoRelacion;
    }

    public void setTipoRelacion(java.lang.String tipoRelacion)
    {
        this.tipoRelacion = tipoRelacion;
    }

    private java.lang.String vocabName;

    public java.lang.String getVocabName()
    {
        return this.vocabName;
    }

    public void setVocabName(java.lang.String vocabName)
    {
        this.vocabName = vocabName;
    }

}