// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateSearchEmbeddedValueList.vsl in andromda-spring-cartridge.
//
package es.pode.contenidos.negocio;

/**
 * Stores the embedded values and asssociations of all entities in the system by type.  
 * Is used to determine the appropriate parameter name when an embedded value's property 
 * is referenced as the attribute to search by (as opposed to an association).
 * 
 * @author Chad Brandon
 */
public class CriteriaSearchProperties
{
    private static final java.util.Map embeddedValuesByType = new java.util.HashMap();
    private static final java.util.Map navigableAssociationEndsByType = new java.util.HashMap();
    
    static
    {
        initialize1();
        initialize2();
        initialize3();
        initialize4();
        initialize5();
        initialize6();
        initialize7();
        initialize8();
        initialize9();
        initialize10();
        initialize11();
    }
    
    private static final void initialize1()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.noticias.dominio.CategoriaIdiomaNoticiaImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.noticias.dominio.CategoriaIdiomaNoticiaImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {

                }
            )
        );
    }
    
    private static final void initialize2()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.noticias.dominio.NoticiaImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.noticias.dominio.NoticiaImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("descripcionNoticia", es.pode.contenidos.negocio.noticias.dominio.DescripcionNoticiaImpl.class), 
                    new AssociationType("categoria", es.pode.contenidos.negocio.noticias.dominio.CategoriaNoticiaImpl.class)
                }
            )
        );
    }
    
    private static final void initialize3()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.descargas.dominio.DescargaImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.descargas.dominio.DescargaImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("descripcion", es.pode.contenidos.negocio.descargas.dominio.DescDescargaImpl.class)
                }
            )
        );
    }
    
    private static final void initialize4()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.noticias.dominio.DescripcionNoticiaImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.noticias.dominio.DescripcionNoticiaImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {

                }
            )
        );
    }
    
    private static final void initialize5()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.faqs.dominio.CategoriaFaqImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.faqs.dominio.CategoriaFaqImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("categoriaIdioma", es.pode.contenidos.negocio.faqs.dominio.CategoriaIdiomaFaqImpl.class)
                }
            )
        );
    }
    
    private static final void initialize6()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.faqs.dominio.DescripcionFaqImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.faqs.dominio.DescripcionFaqImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {

                }
            )
        );
    }
    
    private static final void initialize7()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.faqs.dominio.FaqImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.faqs.dominio.FaqImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("categoria", es.pode.contenidos.negocio.faqs.dominio.CategoriaFaqImpl.class), 
                    new AssociationType("descripcionFaq", es.pode.contenidos.negocio.faqs.dominio.DescripcionFaqImpl.class)
                }
            )
        );
    }
    
    private static final void initialize8()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.noticias.dominio.CategoriaNoticiaImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.noticias.dominio.CategoriaNoticiaImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("categoriaIdioma", es.pode.contenidos.negocio.noticias.dominio.CategoriaIdiomaNoticiaImpl.class)
                }
            )
        );
    }
    
    private static final void initialize9()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.descargas.dominio.DescDescargaImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.descargas.dominio.DescDescargaImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("descarga", es.pode.contenidos.negocio.descargas.dominio.DescargaImpl.class)
                }
            )
        );
    }
    
    private static final void initialize10()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.faqs.dominio.CategoriaIdiomaFaqImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.faqs.dominio.CategoriaIdiomaFaqImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {

                }
            )
        );
    }
    
    private static final void initialize11()
    {
        embeddedValuesByType.put(
            es.pode.contenidos.negocio.generacionDinamica.dominio.ContenidoODEImpl.class,
            null);
        navigableAssociationEndsByType.put(
            es.pode.contenidos.negocio.generacionDinamica.dominio.ContenidoODEImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {

                }
            )
        );
    }
    
    /**
     * Attempts to get the embedded value list for the given type (or returns null
     * if one doesn't exist).
     * 
     * @param type the type of which to retrieve the value.
     * @return the collection of embedded value names.
     */
    public static java.util.Collection getEmbeddedValues(final Class type)
    {
        return (java.util.Collection)embeddedValuesByType.get(type);
    }
    
    /**
     * Gets the type of the navigable association end given the <code>ownerType</code>
     * and <code>name</code>
     *
     * @param ownerType the owner of the association.
     * @param name the name of the association end to find.
     * @return the type of the association end.
     */
    public static Class getNavigableAssociationEndType(final Class ownerType, final String name)
    {
        final java.util.Collection ends = (java.util.Collection)navigableAssociationEndsByType.get(ownerType);
        final AssociationType type = (AssociationType)org.apache.commons.collections.CollectionUtils.find(
            ends,
            new org.apache.commons.collections.Predicate()
            {
                public boolean evaluate(final Object object)
                {
                    return ((AssociationType)object).name.equals(name);
                }
            });
        return type != null ? type.type : null;
    }

    /**
     * A private class storing the association name and type.
     */    
    protected static final class AssociationType
    {
        protected AssociationType(final String name, final Class type)
        {
            this.name = name;
            this.type = type;
        }
        protected String name;
        protected Class type;
    }
}