// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SearchCriteria.vsl in andromda-spring-cartridge.
//
package es.pode.modificador.negocio.dominio;

/**
 * 
 */
public class ModificacionOdeCriteria
    implements java.io.Serializable
{

  /**
   * Constructor por defecto
   */
    public ModificacionOdeCriteria()
    {
    }

    /**
     * Constructor taking all properties.
      * @param pathOriginal java.lang.String
      * @param status es.pode.modificador.negocio.utilidades.EstadosTarea
      * @param pathBackup java.lang.String
     */
    public ModificacionOdeCriteria(
        java.lang.String pathOriginal,
        es.pode.modificador.negocio.utilidades.EstadosTarea status,
        java.lang.String pathBackup)

    {
        this.pathOriginal = pathOriginal;
        this.status = status;
        this.pathBackup = pathBackup;
    }

    /**
     * Copies constructor from other ModificacionOdeCriteria
      * @param otherBean ModificacionOdeCriteria
     */
    public ModificacionOdeCriteria(ModificacionOdeCriteria otherBean)
    {
        if (otherBean != null)
        {
            this.pathOriginal = otherBean.getPathOriginal();
            this.status = otherBean.getStatus();
            this.pathBackup = otherBean.getPathBackup();
        }
    }

    /**
     * The first result to retrieve.
     */
    private java.lang.Integer firstResult;

    /**
     * Gets the first result to retrieve.
     *
     * @return the first result to retrieve
     */
    public java.lang.Integer getFirstResult()
    {
        return this.firstResult;
    }

    /**
     * Sets the first result to retrieve.
     *
     * @param firstResult the first result to retrieve
     */
    public void setFirstResult(java.lang.Integer firstResult)
    {
        this.firstResult = firstResult;
    }

    /**
     * The fetch size.
     */
    private java.lang.Integer fetchSize;

    /**
     * Gets the fetch size.
     *
     * @return the fetch size
     */
    public java.lang.Integer getFetchSize()
    {
        return this.fetchSize;
    }

    /**
     * Sets the fetch size.
     *
     * @param fetchSize the fetch size
     */
    public void setFetchSize(java.lang.Integer fetchSize)
    {
        this.fetchSize = fetchSize;
    }

    /**
     * The maximum size of the result set.
     */
    private java.lang.Integer maximumResultSize;

    /**
     * Gets the maximum size of the search result.
     *
     * @return the maximum size of the search result.
     */
    public java.lang.Integer getMaximumResultSize()
    {
        return this.maximumResultSize;
    }

    /**
     * Sets the maxmimum size of the result.
     *
     * @param maximumResultSize A number indicating how many results will be returned.
     */
    public void setMaximumResultSize(java.lang.Integer maximumResultSize)
    {
        this.maximumResultSize = maximumResultSize;
    }

    private java.lang.String pathOriginal;

    public java.lang.String getPathOriginal()
    {
        return this.pathOriginal;
    }

    public void setPathOriginal(java.lang.String pathOriginal)
    {
        this.pathOriginal = pathOriginal;
    }

    private es.pode.modificador.negocio.utilidades.EstadosTarea status;

    public es.pode.modificador.negocio.utilidades.EstadosTarea getStatus()
    {
        return this.status;
    }

    public void setStatus(es.pode.modificador.negocio.utilidades.EstadosTarea status)
    {
        this.status = status;
    }

    private java.lang.String pathBackup;

    public java.lang.String getPathBackup()
    {
        return this.pathBackup;
    }

    public void setPathBackup(java.lang.String pathBackup)
    {
        this.pathBackup = pathBackup;
    }

}