// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.fuentestaxonomicas.negocio.servicio;

/**
 * <p>
 * Representa un taxon particular dentro de una taxonomia. Esta
 * compuesto por un identificador, un valor y un campo para
 * identificar si el taxon es hoja dentro de la taxonomia.
 * </p>
 */
public class TaxonVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public TaxonVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param id  Identificador del taxon dentro de la taxonomia a la que pertenece.
     * @param valorTax  Valor del taxon en la taxonomia a la que pertenece.
     * @param esHoja  Flag que indica si el taxon tiene descendientes en la taxonomia a la que pertenece.
     * @param vocabName  
     * @param tipoRelacion  
     */
    public TaxonVO(
        java.lang.String id,
        java.lang.String valorTax,
        java.lang.Boolean esHoja,
        java.lang.String vocabName,
        java.lang.String tipoRelacion)

    {
        this.id = id;
        this.valorTax = valorTax;
        this.esHoja = esHoja;
        this.vocabName = vocabName;
        this.tipoRelacion = tipoRelacion;
    }

    /**
     * Copies constructor from other TaxonVO
     * @param otherBean TaxonVO 
     */
    public TaxonVO(TaxonVO otherBean)
    {
        if (otherBean != null)
        {
            this.id = otherBean.getId();
            this.valorTax = otherBean.getValorTax();
            this.esHoja = otherBean.getEsHoja();
            this.vocabName = otherBean.getVocabName();
            this.tipoRelacion = otherBean.getTipoRelacion();
        }
    }

    private java.lang.String id;

    /**
     * <p>
     * Identificador del taxon dentro de la taxonomia a la que
     * pertenece.
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getId()
    {
        return this.id;
    }

    /**
   * <p>
   * Identificador del taxon dentro de la taxonomia a la que
   * pertenece.
   * </p>
     *  @param id  Identificador del taxon dentro de la taxonomia a la que pertenece.  
     */
    public void setId(java.lang.String id)
    {
        this.id = id;
    }

    private java.lang.String valorTax;

    /**
     * <p>
     * Valor del taxon en la taxonomia a la que pertenece.
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getValorTax()
    {
        return this.valorTax;
    }

    /**
   * <p>
   * Valor del taxon en la taxonomia a la que pertenece.
   * </p>
     *  @param valorTax  Valor del taxon en la taxonomia a la que pertenece.  
     */
    public void setValorTax(java.lang.String valorTax)
    {
        this.valorTax = valorTax;
    }

    private java.lang.Boolean esHoja;

    /**
     * <p>
     * Flag que indica si el taxon tiene descendientes en la taxonomia
     * a la que pertenece.
     * </p>
     * @return java.lang.Boolean
     */
    public java.lang.Boolean getEsHoja()
    {
        return this.esHoja;
    }

    /**
   * <p>
   * Flag que indica si el taxon tiene descendientes en la taxonomia
   * a la que pertenece.
   * </p>
     *  @param esHoja  Flag que indica si el taxon tiene descendientes en la taxonomia a la que pertenece.  
     */
    public void setEsHoja(java.lang.Boolean esHoja)
    {
        this.esHoja = esHoja;
    }

    private java.lang.String vocabName;

    public java.lang.String getVocabName()
    {
        return this.vocabName;
    }

    public void setVocabName(java.lang.String vocabName)
    {
        this.vocabName = vocabName;
    }

    private java.lang.String tipoRelacion;

    public java.lang.String getTipoRelacion()
    {
        return this.tipoRelacion;
    }

    public void setTipoRelacion(java.lang.String tipoRelacion)
    {
        this.tipoRelacion = tipoRelacion;
    }

}