// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: Enumeration.vsl in andromda-java-cartridge.
//
package es.pode.fuentestaxonomicas.negocio.servicio;

/**
 * 
 */
public class TipoVdex
    implements java.io.Serializable
{
    /**
     * 
     */
    public static final TipoVdex ARBOL = new TipoVdex("ARBOL");

    /**
     * 
     */
    public static final TipoVdex TESAURO = new TipoVdex("TESAURO");

    /**
     * 
     */
    public static final TipoVdex TAXONOMIA = new TipoVdex("TAXONOMIA");

    /**
     * 
     */
    public static final TipoVdex TESAURO_BACK = new TipoVdex("TESAUROS_BACK");

    private java.lang.String value;

    private TipoVdex(java.lang.String value)
    {
        this.value = value;
    }

    /**
     * The default constructor allowing
     * super classes to access it.
     */
    protected TipoVdex()
    {
    }

    /**
     * @see java.lang.Object#toString()
     */
    public String toString()
    {
        return "" + value;
    }

    /**
     * Creates an instance of TipoVdex from <code>value</code>.
     *
     * @param value the value to create the TipoVdex from.
     */
    public static TipoVdex fromString(java.lang.String value)
    {
        TipoVdex typeValue = (TipoVdex)values.get(value);
        if (typeValue == null)
        {
            throw new IllegalArgumentException(
                "invalid value '" + value + "', possible values are: " + literals);
        }
        return typeValue;
    }

    /**
     * Gets the underlying value of this type safe enumeration.
     *
     * @return the underlying value.
     */
    public java.lang.String getValue()
    {
        return this.value;
    }

    /**
     * @see java.lang.Comparable#compareTo(java.lang.Object)
     */
    public int compareTo(Object that)
    {
        return (this == that) ? 0 : this.getValue().compareTo(
            ((TipoVdex)that).getValue());
    }

    /**
     * Returns an unmodifiable list containing the literals that are known by this enumeration.
     *
     * @return A List containing the actual literals defined by this enumeration, this list
     *         can not be modified.
     */
    public static java.util.List literals()
    {
        return literals;
    }

    /**
     * Returns an unmodifiable list containing the names of the literals that are known
     * by this enumeration.
     *
     * @return A List containing the actual names of the literals defined by this
     *         enumeration, this list can not be modified.
     */
    public static java.util.List names()
    {
        return names;
    }

    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    public boolean equals(Object object)
    {
        return (this == object)
            || (object instanceof TipoVdex && ((TipoVdex)object).getValue().equals(
                this.getValue()));
    }

    /**
     * @see java.lang.Object#hashCode()
     */
    public int hashCode()
    {
        return this.getValue().hashCode();
    }

    private static final java.util.Map values = new java.util.HashMap(4, 1);
    private static java.util.List literals = new java.util.ArrayList(4);
    private static java.util.List names = new java.util.ArrayList(4);

    /**
     * Initializes the values.
     */
    static
    {
        values.put(ARBOL.value, ARBOL);
        literals.add(ARBOL.value);
        names.add("ARBOL");
        values.put(TESAURO.value, TESAURO);
        literals.add(TESAURO.value);
        names.add("TESAURO");
        values.put(TAXONOMIA.value, TAXONOMIA);
        literals.add(TAXONOMIA.value);
        names.add("TAXONOMIA");
        values.put(TESAURO_BACK.value, TESAURO_BACK);
        literals.add(TESAURO_BACK.value);
        names.add("TESAURO_BACK");
        literals = java.util.Collections.unmodifiableList(literals);
        names = java.util.Collections.unmodifiableList(names);
    }
}