// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.empaquetador.negocio.servicio;

/**
 * 
 */
public class TransicionVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public TransicionVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param titulo  
     * @param idODE  
     * @param idUsuario  
     */
    public TransicionVO(
        java.lang.String titulo,
        java.lang.String idODE,
        java.lang.String idUsuario)

    {
        this.titulo = titulo;
        this.idODE = idODE;
        this.idUsuario = idUsuario;
    }

    /**
     * Copies constructor from other TransicionVO
     * @param otherBean TransicionVO 
     */
    public TransicionVO(TransicionVO otherBean)
    {
        if (otherBean != null)
        {
            this.titulo = otherBean.getTitulo();
            this.idODE = otherBean.getIdODE();
            this.idUsuario = otherBean.getIdUsuario();
        }
    }

    private java.lang.String titulo;

    public java.lang.String getTitulo()
    {
        return this.titulo;
    }

    public void setTitulo(java.lang.String titulo)
    {
        this.titulo = titulo;
    }

    private java.lang.String idODE;

    public java.lang.String getIdODE()
    {
        return this.idODE;
    }

    public void setIdODE(java.lang.String idODE)
    {
        this.idODE = idODE;
    }

    private java.lang.String idUsuario;

    public java.lang.String getIdUsuario()
    {
        return this.idUsuario;
    }

    public void setIdUsuario(java.lang.String idUsuario)
    {
        this.idUsuario = idUsuario;
    }

}