// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.empaquetador.negocio.servicio;

/**
 * <p>
 * Objeto que contiene los resultados de una llamada al servicio de
 * validación. Es una copia del ValidaVO devuelto por dicho
 * servicio.
 * </p>
 */
public class ValidaVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public ValidaVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param esValidoManifest  Indica si la validacion ha sido superada.
     * @param resultadoValidacion  Contiene los códigos de los mensajes devueltos por Validacion separados por ';'.
     * @param rutaManifest  Ruta en la que se encuentra almacenado el imsmanifest.xml
     */
    public ValidaVO(
        java.lang.Boolean esValidoManifest,
        java.lang.String resultadoValidacion,
        java.lang.String rutaManifest)

    {
        this.esValidoManifest = esValidoManifest;
        this.resultadoValidacion = resultadoValidacion;
        this.rutaManifest = rutaManifest;
    }

    /**
     * Copies constructor from other ValidaVO
     * @param otherBean ValidaVO 
     */
    public ValidaVO(ValidaVO otherBean)
    {
        if (otherBean != null)
        {
            this.esValidoManifest = otherBean.getEsValidoManifest();
            this.resultadoValidacion = otherBean.getResultadoValidacion();
            this.rutaManifest = otherBean.getRutaManifest();
        }
    }

    private java.lang.Boolean esValidoManifest;

    /**
     * <p>
     * Indica si la validacion ha sido superada.
     * </p>
     * @return java.lang.Boolean
     */
    public java.lang.Boolean getEsValidoManifest()
    {
        return this.esValidoManifest;
    }

    /**
   * <p>
   * Indica si la validacion ha sido superada.
   * </p>
     *  @param esValidoManifest  Indica si la validacion ha sido superada.  
     */
    public void setEsValidoManifest(java.lang.Boolean esValidoManifest)
    {
        this.esValidoManifest = esValidoManifest;
    }

    private java.lang.String resultadoValidacion;

    /**
     * <p>
     * Contiene los códigos de los mensajes devueltos por Validacion
     * separados por ';'.
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getResultadoValidacion()
    {
        return this.resultadoValidacion;
    }

    /**
   * <p>
   * Contiene los códigos de los mensajes devueltos por Validacion
   * separados por ';'.
   * </p>
     *  @param resultadoValidacion  Contiene los códigos de los mensajes devueltos por Validacion separados por ';'.  
     */
    public void setResultadoValidacion(java.lang.String resultadoValidacion)
    {
        this.resultadoValidacion = resultadoValidacion;
    }

    private java.lang.String rutaManifest;

    /**
     * <p>
     * Ruta en la que se encuentra almacenado el imsmanifest.xml
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getRutaManifest()
    {
        return this.rutaManifest;
    }

    /**
   * <p>
   * Ruta en la que se encuentra almacenado el imsmanifest.xml
   * </p>
     *  @param rutaManifest  Ruta en la que se encuentra almacenado el imsmanifest.xml  
     */
    public void setRutaManifest(java.lang.String rutaManifest)
    {
        this.rutaManifest = rutaManifest;
    }

}