// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package es.pode.contenidos.negocio.noticias.dominio;

/**
 * <p>
 * Entity que representa la categoría traducida al idioma
 * correspondiente.
 * </p>
 */
public abstract class CategoriaIdiomaNoticia
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8419192327739557301L;

    private java.lang.Long id;

    /**
     * <p>
     * Identificador autogenerado por la base de datos.
     * </p>
     */
    public java.lang.Long getId()
    {
        return this.id;
    }

    public void setId(java.lang.Long id)
    {
        this.id = id;
    }

    private java.lang.String nombreCategoria;

    /**
     * <p>
     * Nombre de la categoría traducida al idioma correspondiente.
     * </p>
     */
    public java.lang.String getNombreCategoria()
    {
        return this.nombreCategoria;
    }

    public void setNombreCategoria(java.lang.String nombreCategoria)
    {
        this.nombreCategoria = nombreCategoria;
    }

    private java.lang.String idioma;

    /**
     * <p>
     * Idioma en el que se traduce la categoría.
     * </p>
     */
    public java.lang.String getIdioma()
    {
        return this.idioma;
    }

    public void setIdioma(java.lang.String idioma)
    {
        this.idioma = idioma;
    }

    /**
     * Returns <code>true</code> if the argument is an CategoriaIdiomaNoticia instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof CategoriaIdiomaNoticia))
        {
            return false;
        }
        final CategoriaIdiomaNoticia that = (CategoriaIdiomaNoticia)object;
        if (this.id == null || that.id == null || !this.id.equals(that.id))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link es.pode.contenidos.negocio.noticias.dominio.CategoriaIdiomaNoticia}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link es.pode.contenidos.negocio.noticias.dominio.CategoriaIdiomaNoticia}.
         */
        public static es.pode.contenidos.negocio.noticias.dominio.CategoriaIdiomaNoticia newInstance()
        {
            return new es.pode.contenidos.negocio.noticias.dominio.CategoriaIdiomaNoticiaImpl();
        }
    }

// HibernateEntity.vsl merge-point
}