// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SearchCriteria.vsl in andromda-spring-cartridge.
//
package es.pode.contenidos.negocio.noticias.dominio;

/**
 * <p>
 * Criteria que filtra la búsqueda de noticias a sólo las que
 * tengan una descripción noticia en el idioma correspondiente.
 * </p>
 */
public class NoticiasPorIdiomaCriteria
    implements java.io.Serializable
{

    public NoticiasPorIdiomaCriteria()
    {
    }

    /**
     * Constructor taking all properties.
     */
    public NoticiasPorIdiomaCriteria(
        java.util.Date fechaPublicacion,
        es.pode.contenidos.negocio.noticias.dominio.DescripcionNoticia descripcionNoticia)

    {
        this.fechaPublicacion = fechaPublicacion;
        this.descripcionNoticia = descripcionNoticia;
    }

    /**
     * Copies constructor from other NoticiasPorIdiomaCriteria
     */
    public NoticiasPorIdiomaCriteria(NoticiasPorIdiomaCriteria otherBean)
    {
        if (otherBean != null)
        {
            this.fechaPublicacion = otherBean.getFechaPublicacion();
            this.descripcionNoticia = otherBean.getDescripcionNoticia();
        }
    }

    /**
     * The first result to retrieve.
     */
    private java.lang.Integer firstResult;

    /**
     * Gets the first result to retrieve.
     *
     * @return the first result to retrieve
     */
    public java.lang.Integer getFirstResult()
    {
        return this.firstResult;
    }

    /**
     * Sets the first result to retrieve.
     *
     * @param firstResult the first result to retrieve
     */
    public void setFirstResult(java.lang.Integer firstResult)
    {
        this.firstResult = firstResult;
    }

    /**
     * The fetch size.
     */
    private java.lang.Integer fetchSize;

    /**
     * Gets the fetch size.
     *
     * @return the fetch size
     */
    public java.lang.Integer getFetchSize()
    {
        return this.fetchSize;
    }

    /**
     * Sets the fetch size.
     *
     * @param fetchSize the fetch size
     */
    public void setFetchSize(java.lang.Integer fetchSize)
    {
        this.fetchSize = fetchSize;
    }

    /**
     * The maximum size of the result set.
     */
    private java.lang.Integer maximumResultSize;

    /**
     * Gets the maximum size of the search result.
     *
     * @return the maximum size of the search result.
     */
    public java.lang.Integer getMaximumResultSize()
    {
        return this.maximumResultSize;
    }

    /**
     * Sets the maxmimum size of the result.
     *
     * @param maximumResultSize A number indicating how many results will be returned.
     */
    public void setMaximumResultSize(java.lang.Integer maximumResultSize)
    {
        this.maximumResultSize = maximumResultSize;
    }

    private java.util.Date fechaPublicacion;

    /**
     * <p>
     * Fecha de publicación de la noticia.
     * </p>
     */
    public java.util.Date getFechaPublicacion()
    {
        return this.fechaPublicacion;
    }

    public void setFechaPublicacion(java.util.Date fechaPublicacion)
    {
        this.fechaPublicacion = fechaPublicacion;
    }

    private es.pode.contenidos.negocio.noticias.dominio.DescripcionNoticia descripcionNoticia;

    /**
     * 
     */
    public es.pode.contenidos.negocio.noticias.dominio.DescripcionNoticia getDescripcionNoticia()
    {
        return this.descripcionNoticia;
    }

    public void setDescripcionNoticia(es.pode.contenidos.negocio.noticias.dominio.DescripcionNoticia descripcionNoticia)
    {
        this.descripcionNoticia = descripcionNoticia;
    }

}