// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.planificador.negocio.servicios;

/**
 * 
 */
public class TareaReindexadoVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public TareaReindexadoVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param trabajo  Nombre del trabajo
     * @param grupoTrabajo  
     * @param trigger  
     * @param grupoTrigger  
     * @param cron  
     * @param periodicidad  
     * @param fechaInicio  
     * @param usuario  
     * @param repositorioIndices  Identificador del repositorio de ínices que se va a indexar
     * @param tipoTarea  
     * @param msgReindexado  
     * @param msgNoReindexado  
     * @param msgDescripcionTrabajo  
     * @param error  Campo identificativo del error. Sólo tendrá algún valor si se ha producido algún error.
     */
    public TareaReindexadoVO(
        java.lang.String trabajo,
        java.lang.String grupoTrabajo,
        java.lang.String trigger,
        java.lang.String grupoTrigger,
        java.lang.String cron,
        java.lang.String periodicidad,
        java.util.Calendar fechaInicio,
        java.lang.String usuario,
        java.lang.String repositorioIndices,
        java.lang.String tipoTarea,
        java.lang.String msgReindexado,
        java.lang.String msgNoReindexado,
        java.lang.String msgDescripcionTrabajo,
        java.lang.String error)

    {
        this.trabajo = trabajo;
        this.grupoTrabajo = grupoTrabajo;
        this.trigger = trigger;
        this.grupoTrigger = grupoTrigger;
        this.cron = cron;
        this.periodicidad = periodicidad;
        this.fechaInicio = fechaInicio;
        this.usuario = usuario;
        this.repositorioIndices = repositorioIndices;
        this.tipoTarea = tipoTarea;
        this.msgReindexado = msgReindexado;
        this.msgNoReindexado = msgNoReindexado;
        this.msgDescripcionTrabajo = msgDescripcionTrabajo;
        this.error = error;
    }

    /**
     * Copies constructor from other TareaReindexadoVO
     * @param otherBean TareaReindexadoVO 
     */
    public TareaReindexadoVO(TareaReindexadoVO otherBean)
    {
        if (otherBean != null)
        {
            this.trabajo = otherBean.getTrabajo();
            this.grupoTrabajo = otherBean.getGrupoTrabajo();
            this.trigger = otherBean.getTrigger();
            this.grupoTrigger = otherBean.getGrupoTrigger();
            this.cron = otherBean.getCron();
            this.periodicidad = otherBean.getPeriodicidad();
            this.fechaInicio = otherBean.getFechaInicio();
            this.usuario = otherBean.getUsuario();
            this.repositorioIndices = otherBean.getRepositorioIndices();
            this.tipoTarea = otherBean.getTipoTarea();
            this.msgReindexado = otherBean.getMsgReindexado();
            this.msgNoReindexado = otherBean.getMsgNoReindexado();
            this.msgDescripcionTrabajo = otherBean.getMsgDescripcionTrabajo();
            this.error = otherBean.getError();
        }
    }

    private java.lang.String trabajo;

    /**
     * <p>
     * Nombre del trabajo
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getTrabajo()
    {
        return this.trabajo;
    }

    /**
   * <p>
   * Nombre del trabajo
   * </p>
     *  @param trabajo  Nombre del trabajo  
     */
    public void setTrabajo(java.lang.String trabajo)
    {
        this.trabajo = trabajo;
    }

    private java.lang.String grupoTrabajo;

    public java.lang.String getGrupoTrabajo()
    {
        return this.grupoTrabajo;
    }

    public void setGrupoTrabajo(java.lang.String grupoTrabajo)
    {
        this.grupoTrabajo = grupoTrabajo;
    }

    private java.lang.String trigger;

    public java.lang.String getTrigger()
    {
        return this.trigger;
    }

    public void setTrigger(java.lang.String trigger)
    {
        this.trigger = trigger;
    }

    private java.lang.String grupoTrigger;

    public java.lang.String getGrupoTrigger()
    {
        return this.grupoTrigger;
    }

    public void setGrupoTrigger(java.lang.String grupoTrigger)
    {
        this.grupoTrigger = grupoTrigger;
    }

    private java.lang.String cron;

    public java.lang.String getCron()
    {
        return this.cron;
    }

    public void setCron(java.lang.String cron)
    {
        this.cron = cron;
    }

    private java.lang.String periodicidad;

    public java.lang.String getPeriodicidad()
    {
        return this.periodicidad;
    }

    public void setPeriodicidad(java.lang.String periodicidad)
    {
        this.periodicidad = periodicidad;
    }

    private java.util.Calendar fechaInicio;

    public java.util.Calendar getFechaInicio()
    {
        return this.fechaInicio;
    }

    public void setFechaInicio(java.util.Calendar fechaInicio)
    {
        this.fechaInicio = fechaInicio;
    }

    private java.lang.String usuario;

    public java.lang.String getUsuario()
    {
        return this.usuario;
    }

    public void setUsuario(java.lang.String usuario)
    {
        this.usuario = usuario;
    }

    private java.lang.String repositorioIndices;

    /**
     * <p>
     * Identificador del repositorio de ínices que se va a indexar
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getRepositorioIndices()
    {
        return this.repositorioIndices;
    }

    /**
   * <p>
   * Identificador del repositorio de ínices que se va a indexar
   * </p>
     *  @param repositorioIndices  Identificador del repositorio de ínices que se va a indexar  
     */
    public void setRepositorioIndices(java.lang.String repositorioIndices)
    {
        this.repositorioIndices = repositorioIndices;
    }

    private java.lang.String tipoTarea;

    public java.lang.String getTipoTarea()
    {
        return this.tipoTarea;
    }

    public void setTipoTarea(java.lang.String tipoTarea)
    {
        this.tipoTarea = tipoTarea;
    }

    private java.lang.String msgReindexado;

    public java.lang.String getMsgReindexado()
    {
        return this.msgReindexado;
    }

    public void setMsgReindexado(java.lang.String msgReindexado)
    {
        this.msgReindexado = msgReindexado;
    }

    private java.lang.String msgNoReindexado;

    public java.lang.String getMsgNoReindexado()
    {
        return this.msgNoReindexado;
    }

    public void setMsgNoReindexado(java.lang.String msgNoReindexado)
    {
        this.msgNoReindexado = msgNoReindexado;
    }

    private java.lang.String msgDescripcionTrabajo;

    public java.lang.String getMsgDescripcionTrabajo()
    {
        return this.msgDescripcionTrabajo;
    }

    public void setMsgDescripcionTrabajo(java.lang.String msgDescripcionTrabajo)
    {
        this.msgDescripcionTrabajo = msgDescripcionTrabajo;
    }

    private java.lang.String error;

    /**
     * <p>
     * Campo identificativo del error. Sólo tendrá algún valor si se ha
     * producido algún error.
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getError()
    {
        return this.error;
    }

    /**
   * <p>
   * Campo identificativo del error. Sólo tendrá algún valor si se ha
   * producido algún error.
   * </p>
     *  @param error  Campo identificativo del error. Sólo tendrá algún valor si se ha producido algún error.  
     */
    public void setError(java.lang.String error)
    {
        this.error = error;
    }

}