// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.planificador.negocio.servicios;

/**
 * 
 */
public class TrabajoVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public TrabajoVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param trabajo  Nombre del trabajo
     * @param grupoTrabajo  Nombre del grupo al que pertenece el trabajo
     * @param usuario  
     */
    public TrabajoVO(
        java.lang.String trabajo,
        java.lang.String grupoTrabajo,
        java.lang.String usuario)

    {
        this.trabajo = trabajo;
        this.grupoTrabajo = grupoTrabajo;
        this.usuario = usuario;
    }

    /**
     * Copies constructor from other TrabajoVO
     * @param otherBean TrabajoVO 
     */
    public TrabajoVO(TrabajoVO otherBean)
    {
        if (otherBean != null)
        {
            this.trabajo = otherBean.getTrabajo();
            this.grupoTrabajo = otherBean.getGrupoTrabajo();
            this.usuario = otherBean.getUsuario();
        }
    }

    private java.lang.String trabajo;

    /**
     * <p>
     * Nombre del trabajo
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getTrabajo()
    {
        return this.trabajo;
    }

    /**
   * <p>
   * Nombre del trabajo
   * </p>
     *  @param trabajo  Nombre del trabajo  
     */
    public void setTrabajo(java.lang.String trabajo)
    {
        this.trabajo = trabajo;
    }

    private java.lang.String grupoTrabajo;

    /**
     * <p>
     * Nombre del grupo al que pertenece el trabajo
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getGrupoTrabajo()
    {
        return this.grupoTrabajo;
    }

    /**
   * <p>
   * Nombre del grupo al que pertenece el trabajo
   * </p>
     *  @param grupoTrabajo  Nombre del grupo al que pertenece el trabajo  
     */
    public void setGrupoTrabajo(java.lang.String grupoTrabajo)
    {
        this.grupoTrabajo = grupoTrabajo;
    }

    private java.lang.String usuario;

    public java.lang.String getUsuario()
    {
        return this.usuario;
    }

    public void setUsuario(java.lang.String usuario)
    {
        this.usuario = usuario;
    }

}