// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringDao.vsl in andromda-spring-cartridge.
//
package es.pode.publicacion.negocio.dominio;

/**
 * @see es.pode.publicacion.negocio.dominio.Estado
 */
public interface EstadoDao
{
    /**
     * This constant is used as a transformation flag; entities can be converted automatically into value objects
     * or other types, different methods in a class implementing this interface support this feature: look for
     * an <code>int</code> parameter called <code>transform</code>.
     * <p/>
     * This specific flag denotes no transformation will occur.
     */
    public final static int TRANSFORM_NONE = 0;

    /**
     * This constant is used as a transformation flag; entities can be converted automatically into value objects
     * or other types, different methods in a class implementing this interface support this feature: look for
     * an <code>int</code> parameter called <code>transform</code>.
     * <p/>
     * This specific flag denotes entities must be transformed into objects of type
     * {@link es.pode.publicacion.negocio.servicios.EstadoVO}.
     */
    public final static int TRANSFORM_ESTADOVO = 1;
    
    
    /**
     * Converts this DAO's entity to an object of type {@link es.pode.publicacion.negocio.servicios.EstadoVO}.
     * @param entity es.pode.publicacion.negocio.dominio.Estado
     * @return es.pode.publicacion.negocio.servicios.EstadoVO     
     */
    public es.pode.publicacion.negocio.servicios.EstadoVO toEstadoVO(es.pode.publicacion.negocio.dominio.Estado entity);

    /**
     * Converts this DAO's entity to a Collection of instances of type {@link es.pode.publicacion.negocio.servicios.EstadoVO}.
     * @param entities java.util.Collection
     */
    public void toEstadoVOCollection(java.util.Collection entities);

    public es.pode.publicacion.negocio.dominio.Estado fromEstadoVO(es.pode.publicacion.negocio.servicios.EstadoVO vo);
    
    public void fromEstadoVO(es.pode.publicacion.negocio.servicios.EstadoVO vo, es.pode.publicacion.negocio.dominio.Estado entity);    


    /**
     * Loads an instance of es.pode.publicacion.negocio.dominio.Estado from the persistent store.
     * @param id java.lang.Long
     * @return es.pode.publicacion.negocio.dominio.Estado     
     */
    public es.pode.publicacion.negocio.dominio.Estado load(java.lang.Long id);

    /**
     * <p>
     *   Does the same thing as {@link #load(java.lang.Long)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined in this class then the result <strong>WILL BE</strong> passed through an operation which can
     *   optionally transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     * @param transform int   
     * @param id the identifier of the entity to load.
     * @return either the entity or the object transformed from the entity.
     */
    public Object load(int transform, java.lang.Long id);
    
    /**
     * Loads all entities of type {@link es.pode.publicacion.negocio.dominio.Estado}. 
     * 
     * @return the loaded entities.
     */
    public java.util.Collection loadAll();
    
    /** 
     * <p>
     *   Does the same thing as {@link #loadAll()} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     * 
     * @param transform the flag indicating what transformation to use.
     * @return the loaded entities.
     */
    public java.util.Collection loadAll(final int transform);

    /**
     * Creates an instance of es.pode.publicacion.negocio.dominio.Estado and adds it to the persistent store.
     * @param estado es.pode.publicacion.negocio.dominio.Estado
     * @return es.pode.publicacion.negocio.dominio.Estado     
     */
    public es.pode.publicacion.negocio.dominio.Estado create(es.pode.publicacion.negocio.dominio.Estado estado);

    /**
     * <p>
     *   Does the same thing as {@link #create(es.pode.publicacion.negocio.dominio.Estado)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     * @param transform int
     * @param estado es.pode.publicacion.negocio.dominio.Estado
     * @return Object     
     */
    public Object create(int transform, es.pode.publicacion.negocio.dominio.Estado estado);

    /**
     * Creates a new instance of es.pode.publicacion.negocio.dominio.Estado and adds
     * from the passed in <code>entities</code> collection
     *
     * @param entities the collection of es.pode.publicacion.negocio.dominio.Estado
     *        instances to create.
     *
     * @return the created instances.
     */
    public java.util.Collection create(java.util.Collection entities);

    /**
     * <p>
     *   Does the same thing as {@link #create(es.pode.publicacion.negocio.dominio.Estado)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entities (into value objects for example).  By default, transformation does
     *   not occur.
     * </p>
     * @param transform int
     * @param entities java.util.Collection
     * @return java.util.Collection        
     */
    public java.util.Collection create(int transform, java.util.Collection entities);

    /**
     * <p>
     *   Creates a new <code>es.pode.publicacion.negocio.dominio.Estado</code>
     *   instance from <strong>all</strong> attributes and adds it to
     *   the persistent store.
     * </p>
					 * @param nombre java.lang.String  
			     * @return es.pode.publicacion.negocio.dominio.Estado
     */
    public es.pode.publicacion.negocio.dominio.Estado create(
					java.lang.String nombre 
			);



    /**
     * <p>
     *   Does the same thing as {@link #create(java.lang.String)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   the returned entity will <strong>NOT</strong> be transformed.  If this flag is any of the other constants
     *   defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entity (into a value object for example).  By default, transformation does
     *   not occur.
     * </p>
     * @param int
					 * @param nombre java.lang.String 
			     * @return Object
     */
    public Object create(int transform,
					java.lang.String nombre 
			);



    /**
     * Updates the <code>estado</code> instance in the persistent store.
     * @param estado es.pode.publicacion.negocio.dominio.Estado
     */
    public void update(es.pode.publicacion.negocio.dominio.Estado estado);

    /**
     * Updates all instances in the <code>entities</code> collection in the persistent store.
     * @param entities java.util.Collection
     */
    public void update(java.util.Collection entities);

    /**
     * Removes the instance of es.pode.publicacion.negocio.dominio.Estado from the persistent store.
     * @param estado es.pode.publicacion.negocio.dominio.Estado  
     */
    public void remove(es.pode.publicacion.negocio.dominio.Estado estado);

    /**
     * Removes the instance of es.pode.publicacion.negocio.dominio.Estado having the given
     * <code>identifier</code> from the persistent store.
     * @param id java.lang.Long
     */
    public void remove(java.lang.Long id);

    /**
     * Removes all entities in the given <code>entities<code> collection.
     * @param entities java.util.Collection
     */
    public void remove(java.util.Collection entities);

  /**
   * <p>
   * Este metodo devuelve el estado por el que se le pregunta.
   * </p>
      * @param nombre  Nombre del estado por el que se pregunta.
      * @return es.pode.publicacion.negocio.dominio.Estado
   */
    public es.pode.publicacion.negocio.dominio.Estado obtenEstadoPorNombre(java.lang.String nombre);

    /**
     * <p>
     *   Does the same thing as {@link #obtenEstadoPorNombre(java.lang.String)} with an
     *   additional argument called <code>queryString</code>.  This <code>queryString</code>
     *   argument allows you to override the query string defined in {@link #obtenEstadoPorNombre(java.lang.String)}.
     * </p>
     * @param queryString String
        * @param nombre  Nombre del estado por el que se pregunta.
        * @return es.pode.publicacion.negocio.dominio.Estado
     */
    public es.pode.publicacion.negocio.dominio.Estado obtenEstadoPorNombre(String queryString, java.lang.String nombre);

    /**
     * <p>
     *   Does the same thing as {@link #obtenEstadoPorNombre(java.lang.String)} with an
     *   additional flag called <code>transform</code>.  If this flag is set to <code>TRANSFORM_NONE</code> then
     *   finder results will <strong>NOT</strong> be transformed during retrieval.
     *   If this flag is any of the other constants defined here
     *   then finder results <strong>WILL BE</strong> passed through an operation which can optionally
     *   transform the entities (into value objects for example).  By default, transformation does
     *   not occur.
     * </p>
     * @param transform int
        * @param nombre  Nombre del estado por el que se pregunta.
        * @return Object
     */
    public Object obtenEstadoPorNombre(int transform, java.lang.String nombre);

    /**
     * <p>
     *   Does the same thing as {@link #obtenEstadoPorNombre(boolean, java.lang.String)} with an
     *   additional argument called <code>queryString</code>.  This <code>queryString</code>
     *   argument allows you to override the query string defined in {@link #obtenEstadoPorNombre(int, java.lang.String nombre)}.
     * </p>
     * @param transform int
     * @param queryString String     
        * @param nombre  Nombre del estado por el que se pregunta.
        * @return Object
     */
    public Object obtenEstadoPorNombre(int transform, String queryString, java.lang.String nombre);

}
