// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.modificador.negocio.servicio.vo;

/**
 * <p>
 * Bean con los datos necesarios para pintar un formulario de
 * modificar termino lomes.
 * </p>
 */
public class FormularioModificarVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public FormularioModificarVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param idTermino  Termino LOM-ES identificador por el índice (p.e. termino idioma del general = 1.3)
     * @param nombreTermino  Termino lomes identificador por los nombres de las etiquetas (valor que se configurara en la configuracion de la tarea) - por ejemplo: lom.general.language
     * @param esCombo  
     * @param opcionesCombo  En caso de que esCombo=true, se cargan en este array las opciones posibles para el idTermino que se desea modificar.
     * @param langString  Indica si el campo es un langstring (el formulario de lenguaje tiene que estar activado).
     * @param esFinal  
     */
    public FormularioModificarVO(
        java.lang.String idTermino,
        java.lang.String nombreTermino,
        java.lang.Boolean esCombo,
        java.lang.String[] opcionesCombo,
        java.lang.Boolean langString,
        java.lang.Boolean esFinal)

    {
        this.idTermino = idTermino;
        this.nombreTermino = nombreTermino;
        this.esCombo = esCombo;
        this.opcionesCombo = opcionesCombo;
        this.langString = langString;
        this.esFinal = esFinal;
    }

    /**
     * Copies constructor from other FormularioModificarVO
     * @param otherBean FormularioModificarVO 
     */
    public FormularioModificarVO(FormularioModificarVO otherBean)
    {
        if (otherBean != null)
        {
            this.idTermino = otherBean.getIdTermino();
            this.nombreTermino = otherBean.getNombreTermino();
            this.esCombo = otherBean.getEsCombo();
            this.opcionesCombo = otherBean.getOpcionesCombo();
            this.langString = otherBean.getLangString();
            this.esFinal = otherBean.getEsFinal();
        }
    }

    private java.lang.String idTermino;

    /**
     * <p>
     * Termino LOM-ES identificador por el índice (p.e. termino idioma
     * del general = 1.3)
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getIdTermino()
    {
        return this.idTermino;
    }

    /**
   * <p>
   * Termino LOM-ES identificador por el índice (p.e. termino idioma
   * del general = 1.3)
   * </p>
     *  @param idTermino  Termino LOM-ES identificador por el índice (p.e. termino idioma del general = 1.3)  
     */
    public void setIdTermino(java.lang.String idTermino)
    {
        this.idTermino = idTermino;
    }

    private java.lang.String nombreTermino;

    /**
     * <p>
     * Termino lomes identificador por los nombres de las etiquetas
     * (valor que se configurara en la configuracion de la tarea) - por
     * ejemplo: lom.general.language
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getNombreTermino()
    {
        return this.nombreTermino;
    }

    /**
   * <p>
   * Termino lomes identificador por los nombres de las etiquetas
   * (valor que se configurara en la configuracion de la tarea) - por
   * ejemplo: lom.general.language
   * </p>
     *  @param nombreTermino  Termino lomes identificador por los nombres de las etiquetas (valor que se configurara en la configuracion de la tarea) - por ejemplo: lom.general.language  
     */
    public void setNombreTermino(java.lang.String nombreTermino)
    {
        this.nombreTermino = nombreTermino;
    }

    private java.lang.Boolean esCombo;

    public java.lang.Boolean getEsCombo()
    {
        return this.esCombo;
    }

    public void setEsCombo(java.lang.Boolean esCombo)
    {
        this.esCombo = esCombo;
    }

    private java.lang.String[] opcionesCombo;

    /**
     * <p>
     * En caso de que esCombo=true, se cargan en este array las
     * opciones posibles para el idTermino que se desea modificar.
     * </p>
     * @return java.lang.String[]
     */
    public java.lang.String[] getOpcionesCombo()
    {
        return this.opcionesCombo;
    }

    /**
   * <p>
   * En caso de que esCombo=true, se cargan en este array las
   * opciones posibles para el idTermino que se desea modificar.
   * </p>
     *  @param opcionesCombo  En caso de que esCombo=true, se cargan en este array las opciones posibles para el idTermino que se desea modificar.  
     */
    public void setOpcionesCombo(java.lang.String[] opcionesCombo)
    {
        this.opcionesCombo = opcionesCombo;
    }

    private java.lang.Boolean langString;

    /**
     * <p>
     * Indica si el campo es un langstring (el formulario de lenguaje
     * tiene que estar activado).
     * </p>
     * @return java.lang.Boolean
     */
    public java.lang.Boolean getLangString()
    {
        return this.langString;
    }

    /**
   * <p>
   * Indica si el campo es un langstring (el formulario de lenguaje
   * tiene que estar activado).
   * </p>
     *  @param langString  Indica si el campo es un langstring (el formulario de lenguaje tiene que estar activado).  
     */
    public void setLangString(java.lang.Boolean langString)
    {
        this.langString = langString;
    }

    private java.lang.Boolean esFinal;

    public java.lang.Boolean getEsFinal()
    {
        return this.esFinal;
    }

    public void setEsFinal(java.lang.Boolean esFinal)
    {
        this.esFinal = esFinal;
    }

}