// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringService.vsl in andromda-spring-cartridge.
//
package es.pode.contenidos.negocio.informes.servicio;

/**
 * 
 */
public interface SrvInformeService
{
    /**
     * 
     */
    public es.pode.contenidos.negocio.informes.servicio.InformeVO[] listarInformes();

    /**
     * 
     */
    public es.pode.contenidos.negocio.informes.servicio.ValidaBajaInformeVO eliminarInforme(java.lang.String[] ficheros);

    /**
     * 
     */
    public javax.activation.DataHandler recuperarInforme(java.lang.String fichero);

    /**
     * 
     */
    public es.pode.contenidos.negocio.informes.servicio.InformeVO[] listarInformesMas();

    /**
     * 
     */
    public javax.activation.DataHandler recuperarInformeMas(java.lang.String fichero);

    /**
     * <p>
     * Metodo para listar los metodos federados
     * </p>
     */
    public es.pode.contenidos.negocio.informes.servicio.InformeVO[] listarInformesFederados();

    /**
     * <p>
     * Metodo para eliminar informes federados
     * </p>
     */
    public es.pode.contenidos.negocio.informes.servicio.ValidaBajaInformeVO eliminarInformeFederado(java.lang.String[] ficheros);

    /**
     * <p>
     * Metod para recuperar los informes federados
     * </p>
     */
    public javax.activation.DataHandler recuperarInformesFederados(java.lang.String fichero);

}
