// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringService.vsl in andromda-spring-cartridge.
//
package es.pode.dri.negocio.servicios.SQI;

/**
 * <p>
 * Esta clase implementa los metodos asincronos de la interfaz SQI.
 * </p>
 */
public interface SrvSQIAsincronoService
{
  /**
   * <p>
   * Este metodo permite realizar ejecuciones de queries en modo
   * asincrono, de manera que el API devuelve los resultados de la
   * query cuando termine de ejecutar la busqueda.
   * </p>
   * <p>
   * Este metodo esta en sintonia con setSourceLocation, el cual se
   * tiene que ejecutar antes para suministar la localizacion donde
   * se van a devolver los resutlados de la query.
   * </p>
      * @param targetSessionID  Identificador de la sesion que se va a utilizar.
         * @param queryStatement  Sentencia a ejecutar en modo asincrono.
         * @param queryID  Identificador de la query que se va a ejecutar. Este identifiacador es un valor suministrado por el cliente del API que lo utiliza para identificar su consulta.
      */
    public void asynchronousQuery(java.lang.String targetSessionID, java.lang.String queryStatement, java.lang.String queryID);

}
