// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.adminusuarios.negocio.servicios;

/**
 * 
 */
public class UsuarioActivoVO
    implements java.io.Serializable
{

    /**
     * Constructor por defecto
     */        
    public UsuarioActivoVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param nombre  
     * @param apellido1  
     * @param apellido2  
     * @param login  
     * @param email  
     * @param idiomaAplicacion  
     * @param idiomaBusqueda  
     * @param tipoEmpaquetador  
     * @param grupos  
     * @param permisos  
     * @param NIF  
     */
    public UsuarioActivoVO(
        java.lang.String nombre,
        java.lang.String apellido1,
        java.lang.String apellido2,
        java.lang.String login,
        java.lang.String email,
        java.lang.String idiomaAplicacion,
        java.lang.String idiomaBusqueda,
        java.lang.String tipoEmpaquetador,
        java.lang.String grupos,
        java.lang.String permisos,
        java.lang.String NIF)

    {
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.login = login;
        this.email = email;
        this.idiomaAplicacion = idiomaAplicacion;
        this.idiomaBusqueda = idiomaBusqueda;
        this.tipoEmpaquetador = tipoEmpaquetador;
        this.grupos = grupos;
        this.permisos = permisos;
        this.NIF = NIF;
    }

    /**
     * Copies constructor from other UsuarioActivoVO
     * @param otherBean UsuarioActivoVO 
     */
    public UsuarioActivoVO(UsuarioActivoVO otherBean)
    {
        if (otherBean != null)
        {
            this.nombre = otherBean.getNombre();
            this.apellido1 = otherBean.getApellido1();
            this.apellido2 = otherBean.getApellido2();
            this.login = otherBean.getLogin();
            this.email = otherBean.getEmail();
            this.idiomaAplicacion = otherBean.getIdiomaAplicacion();
            this.idiomaBusqueda = otherBean.getIdiomaBusqueda();
            this.tipoEmpaquetador = otherBean.getTipoEmpaquetador();
            this.grupos = otherBean.getGrupos();
            this.permisos = otherBean.getPermisos();
            this.NIF = otherBean.getNIF();
        }
    }

    private java.lang.String nombre;

    public java.lang.String getNombre()
    {
        return this.nombre;
    }

    public void setNombre(java.lang.String nombre)
    {
        this.nombre = nombre;
    }

    private java.lang.String apellido1;

    public java.lang.String getApellido1()
    {
        return this.apellido1;
    }

    public void setApellido1(java.lang.String apellido1)
    {
        this.apellido1 = apellido1;
    }

    private java.lang.String apellido2;

    public java.lang.String getApellido2()
    {
        return this.apellido2;
    }

    public void setApellido2(java.lang.String apellido2)
    {
        this.apellido2 = apellido2;
    }

    private java.lang.String login;

    public java.lang.String getLogin()
    {
        return this.login;
    }

    public void setLogin(java.lang.String login)
    {
        this.login = login;
    }

    private java.lang.String email;

    public java.lang.String getEmail()
    {
        return this.email;
    }

    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    private java.lang.String idiomaAplicacion;

    public java.lang.String getIdiomaAplicacion()
    {
        return this.idiomaAplicacion;
    }

    public void setIdiomaAplicacion(java.lang.String idiomaAplicacion)
    {
        this.idiomaAplicacion = idiomaAplicacion;
    }

    private java.lang.String idiomaBusqueda;

    public java.lang.String getIdiomaBusqueda()
    {
        return this.idiomaBusqueda;
    }

    public void setIdiomaBusqueda(java.lang.String idiomaBusqueda)
    {
        this.idiomaBusqueda = idiomaBusqueda;
    }

    private java.lang.String tipoEmpaquetador;

    public java.lang.String getTipoEmpaquetador()
    {
        return this.tipoEmpaquetador;
    }

    public void setTipoEmpaquetador(java.lang.String tipoEmpaquetador)
    {
        this.tipoEmpaquetador = tipoEmpaquetador;
    }

    private java.lang.String grupos;

    public java.lang.String getGrupos()
    {
        return this.grupos;
    }

    public void setGrupos(java.lang.String grupos)
    {
        this.grupos = grupos;
    }

    private java.lang.String permisos;

    public java.lang.String getPermisos()
    {
        return this.permisos;
    }

    public void setPermisos(java.lang.String permisos)
    {
        this.permisos = permisos;
    }

    private java.lang.String NIF;

    public java.lang.String getNIF()
    {
        return this.NIF;
    }

    public void setNIF(java.lang.String NIF)
    {
        this.NIF = NIF;
    }

}