// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package es.pode.adminusuarios.negocio.dominio;

/**
 * 
 */
public abstract class GrupoTrabajo
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7305882636456777939L;

    private java.lang.Long identificador;

    /**
     * <p>
     * identificador del grupo de trabajo
     * </p>
     */
    public java.lang.Long getIdentificador()
    {
        return this.identificador;
    }

    public void setIdentificador(java.lang.Long identificador)
    {
        this.identificador = identificador;
    }
    private java.lang.String nombre;

    /**
     * <p>
     * Nombre del grupo de trabajo
     * </p>
     */
    public java.lang.String getNombre()
    {
        return this.nombre;
    }

    public void setNombre(java.lang.String nombre)
    {
        this.nombre = nombre;
    }
    private java.lang.String descripcion;

    /**
     * <p>
     * Descripción más detallada del grupo de trabajo
     * </p>
     */
    public java.lang.String getDescripcion()
    {
        return this.descripcion;
    }

    public void setDescripcion(java.lang.String descripcion)
    {
        this.descripcion = descripcion;
    }


    /**
     * Returns <code>true</code> if the argument is an GrupoTrabajo instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof GrupoTrabajo))
        {
            return false;
        }
        final GrupoTrabajo that = (GrupoTrabajo)object;
        if (this.identificador == null || that.identificador == null || !this.identificador.equals(that.identificador))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (identificador == null ? 0 : identificador.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link es.pode.adminusuarios.negocio.dominio.GrupoTrabajo}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link es.pode.adminusuarios.negocio.dominio.GrupoTrabajo}.
         */
        public static es.pode.adminusuarios.negocio.dominio.GrupoTrabajo newInstance()
        {
            return new es.pode.adminusuarios.negocio.dominio.GrupoTrabajoImpl();
        }
    }

// HibernateEntity.vsl merge-point
}