// license-header java merge-point
/* Autogenerated by AndroMDA (MessageDrivenBean.vsl) - do not edit */

package es.pode.auditoria.negocio.servicios.jms;

import java.util.Map;


/**
 * Autogenerated JMS message driven EJB class for the SrvAuditoriaRecibirServicio bean.
 * Generated file: es/pode/auditoria/negocio/servicios/jms/SrvAuditoriaRecibirServicio
 */



public interface  SrvAuditoriaRecibirServicio 
{
    

    

    // -------- User Defined Methods  --------------
    

  
  
        public  void registrarBusqueda(es.pode.auditoria.negocio.servicios.BusquedaVO busqueda);
   
 
  
  
        public  void registrarOperacion(es.pode.auditoria.negocio.servicios.OperacionVO operacion);
   
  
 
}